version: '3.7'

services:
  api:
    build: .
    volumes:
      - .:/api
      - /api/node_modules
    env_file:
      - ./.env
    ports:
      - ${PORT}:${PORT}
      # TODO: Consider exposing port 9229 and running with --inspect=0.0.0.0 flag in order to enable debugging
      # - 9229:9229
    environment:
      WAIT_HOSTS: database:27017

  database:
    image: mongo
    restart: always
    env_file:
      - ./.env
    # TODO: Mapped volumes only work on Linux distributions, consider enabling
    # volumes:
    #   - ".${MONGO_DATA_DIR}:${MONGO_DATA_DIR}"
    # command: "mongod --smallfiles --logpath=${MONGO_LOG_FILE}"
    ports:
      - 27017:27017
    expose:
      - 27017
