version: '3.7'

services:
  api:
    build: .
    volumes:
      - .:/api
      - /api/node_modules
    env_file:
      - ./.env
    ports:
      - ${PORT}:${PORT}
      # TODO: Consider exposing port 9229 and running with --inspect=0.0.0.0 flag in order to enable debugging
      # - 9229:9229
    environment:
      WAIT_HOSTS: database:27017

  database:
    image: mongo
    restart: always
    env_file:
      - ./.env
    volumes:
      - ./data:${MONGO_DATA_DIR}
      - ./mongo-init.sh:/docker-entrypoint-initdb.d/mongo-init.sh:ro
    ports:
      - 27017:27017
    expose:
      - 27017
